---
- name: Update fixVersion in Jira
  hosts: localhost
  gather_facts: false

  vars:
    jira_url: "https://jira.astralinux.ru"

  tasks:

    - name: Определить имя ветки
      set_fact:
        branch_name: "{{ awx_webhook_payload.changes[0].ref.displayId }}"

    - name: Вычислить значение fixVersion
      set_fact:
        fix_version: >-
          {{ branch_name | regex_replace('^release[-/]', '') if branch_name.startswith('release') else 'next-release' }}

    - name: Извлечь Jira-ключи из коммитов
      set_fact:
        jira_keys: >-
          {{
            awx_webhook_payload.commits
            | map(attribute='properties.jira-key')
            | select('defined')
            | list
            | flatten
            | unique
          }}

    - name: Обновить fixVersion у задач Jira
      uri:
        url: "{{ jira_url }}/rest/api/2/issue/{{ item }}"
        method: PUT
        user: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        force_basic_auth: true
        headers:
          Content-Type: "application/json"
        body_format: json
        body:
          fields:
            fixVersions:
              - name: "{{ fix_version | trim }}"
      loop: "{{ jira_keys }}"
      loop_control:
        label: "{{ item }}"
