---
- name: Update fixVersion in Jira
  hosts: localhost
  gather_facts: false
  vars:
    jira_user: "{{ ansible_user }}"
    jira_token: "{{ ansible_password }}"

  tasks:
    - name: Debug webhook payload (удалить позже)
      debug:
        var: awx_webhook_payload

    - name: Получить имя ветки из webhook payload
      set_fact:
        branch_name: "{{ awx_webhook_payload.changes[0].ref.displayId }}"

    - name: Определить значение fixVersion
      set_fact:
        fixversion: >-
          {% if branch_name.startswith('release/') %}
            {{ branch_name | regex_replace('^release/', '') }}
          {% elif branch_name in ['main', 'master', 'devel'] %}
            next-release
          {% else %}
            undefined
          {% endif %}

    - name: Собрать список Jira задач из коммитов
      set_fact:
        issue_keys: >-
          {{
            awx_webhook_payload.commits
            | map(attribute='properties')
            | map(attribute='jira-key')
            | select('defined')
            | flatten
            | unique
          }}

    - name: Jira задачи для обновления
      debug:
        var: issue_keys

    - name: Обновить fixVersion в Jira задачах
      uri:
        url: "https://jira.example.com/rest/api/2/issue/{{ item }}"
        method: PUT
        user: "{{ jira_user }}"
        password: "{{ jira_token }}"
        force_basic_auth: yes
        headers:
          Content-Type: "application/json"
        body_format: json
        body:
          fields:
            fixVersions:
              - name: "{{ fixversion }}"
      loop: "{{ issue_keys }}"
      when: fixversion != 'undefined' and issue_keys | length > 0
