---
- name: Update fixVersion in Jira
  hosts: localhost
  gather_facts: false
  vars:
    jira_base_url: "https://jira.astralinux.ru"
    jira_user: "{{ ansible_user }}"
    jira_api_token: "{{ ansible_password }}"
    next_release_name: next-release

  tasks:

    - name: Установить имя ветки из webhook
      set_fact:
        branch_name: "{{ awx_webhook_payload.changes[0].ref.displayId | default('') }}"

    - name: Проверка значения переменной branch_name
      debug:
        msg: "Имя ветки: {{ branch_name }}"

    - name: Получить список всех задач из webhook
      set_fact:
        all_issue_keys: "{{ awx_webhook_payload.commits | map(attribute='properties') | map(attribute='jira-key') | select('defined') | list | flatten | unique }}"

    - name: Проверка найденных задач Jira
      debug:
        var: all_issue_keys

    - name: Определить имя версии (релизной или next-release)
      set_fact:
        version_name: >-
          {% if branch_name.startswith('release/') %}
            {{ branch_name.split('release/')[1] }}
          {% elif branch_name in ['devel', 'master', 'main'] %}
            {{ next_release_name }}
          {% else %}
            ""
          {% endif %}

    - name: Проверка определённого имени версии
      debug:
        msg: "Имя версии: {{ version_name }}"

    - name: Пропустить обновление, если версия не требуется
      meta: end_play
      when: version_name == ""

    - name: Получить список всех версий проекта
      uri:
        url: "{{ jira_base_url }}/rest/api/2/project/{{ awx_webhook_payload.repository.project.key }}/versions"
        method: GET
        user: "{{ jira_user }}"
        password: "{{ jira_api_token }}"
        force_basic_auth: true
        headers:
          Content-Type: "application/json"
        return_content: true
      register: all_versions_response

    - name: Найти ID версии по имени
      set_fact:
        version_id: >-
          {{ (all_versions_response.json | selectattr('name', 'equalto', version_name) | list)[0].id }}
      when: >
        all_versions_response.json | selectattr('name', 'equalto', version_name) | list | length > 0

    - name: Проверка найденного ID версии
      debug:
        msg: "ID версии: {{ version_id }}"
      when: version_id is defined

    - name: Обновить fixVersion у задач Jira
      uri:
        url: "{{ jira_base_url }}/rest/api/2/issue/{{ item }}"
        method: PUT
        user: "{{ jira_user }}"
        password: "{{ jira_api_token }}"
        force_basic_auth: true
        headers:
          Content-Type: "application/json"
        body: |
          {
            "fields": {
              "fixVersions": [
                { "id": "{{ version_id }}" }
              ]
            }
          }
        body_format: json
        status_code: 204
      loop: "{{ all_issue_keys }}"
      when: version_id is defined
