---
- name: Update fixVersion in Jira
  hosts: localhost
  gather_facts: false

  vars:
    jira_url: "https://jira.astralinux.ru"
    fix_version_name: ""
    fix_version_id: ""
    jira_project_key: "AA"
    next_release_version: "next-release"

  tasks:

    - name: Установить имя ветки из webhook или переменной
      set_fact:
        branch_name: "{{ branch_name | default(webhook_payload.changes[0].ref.displayId, true) }}"

    - name: Установить имя версии, если ветка релизная
      set_fact:
        fix_version_name: "{{ branch_name | regex_replace('^release/', '') }}"
      when: branch_name is match('^release/')

    - name: Установить имя версии, если ветка основная (devel, main, master)
      set_fact:
        fix_version_name: "{{ next_release_version }}"
      when: branch_name in ['devel', 'main', 'master']

    - name: Извлечь задачи Jira из названия ветки
      shell: echo "{{ branch_name }}" | grep -Eo '[A-Z]+-[0-9]+'
      register: matched_issues
      changed_when: false

    - name: Получить список задач без дубликатов
      set_fact:
        jira_issues: "{{ matched_issues.stdout_lines | unique }}"
      when: matched_issues.stdout_lines | length > 0

    - name: Получить список всех версий проекта в Jira
      uri:
        url: "https://jira.astralinux.ru/rest/api/2/project/{{ jira_project_key }}/versions"
        method: GET
        user: "{{ jira_username }}"
        password: "{{ jira_password }}"
        force_basic_auth: true
        return_content: true
        status_code: 200
      register: versions_response
      when: fix_version_name != ""

    - name: Найти ID нужной версии
      set_fact:
        fix_version_id: "{{ (versions_response.json | selectattr('name', 'equalto', fix_version_name) | list).0.id }}"
      when: fix_version_name != ""

    - name: Обновить fixVersion у задач Jira
      uri:
        url: "https://jira.astralinux.ru/rest/api/2/issue/{{ item }}"
        method: PUT
        user: "{{ jira_username }}"
        password: "{{ jira_password }}"
        force_basic_auth: true
        headers:
          Content-Type: "application/json"
        body_format: json
        body:
          fields:
            fixVersions:
              - id: "{{ fix_version_id }}"
        status_code: 204
      loop: "{{ jira_issues }}"
      loop_control:
        label: "{{ item }}"
      when: fix_version_id != ""